version: "3.8"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ZOO_ENABLE_AUTH=no
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Можно скопировать init_postgres.sql в /docker-entrypoint-initdb.d

  clickhouse:
    image: clickhouse/clickhouse-server:23
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  aggregator:
    build: ./aggregator
    depends_on:
      - kafka
      - postgres
    environment:
      - PYTHONUNBUFFERED=1
    # Запускать можно вручную (cron), либо в виде постоянного контейнера

  bidder:
    build: ./bidder
    depends_on:
      - kafka
    ports:
      - "8090:8090"

  dsp:
    build: ./dsp
    depends_on:
      - bidder
      - kafka
    ports:
      - "8080:8080"

  ssp:
    build: ./ssp
    depends_on:
      - dsp
      - kafka
    ports:
      - "3002:3002"

  website:
    build: ./website
    depends_on:
      - postgres
      - kafka
    ports:
      - "3001:3001"

volumes:
  postgres-data:
  clickhouse-data:
