apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dsp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dsp
    spec:
      containers:
        - name: dsp
          image: myrepo/dsp:v1.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          env:
            - name: KAFKA_BROKERS
              value: "kafka:9092"
            - name: BIDDER_URL
              value: "http://bidder:8090"
          # и т.д.
